services:
  db:
    image: postgres:latest
    environment:
      - PGPORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -p 5432 -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres?sslmode=disable
    healthcheck:
      test: "curl localhost:8080 | grep running"
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  test:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres?sslmode=disable
    command:
      - bash
      - -c
      - /app/bin/client && curl "http://api:8080/metrics?from_ts=0&to_ts=$$(date +%s)" | grep concurrency
    depends_on:
      api:
          condition: service_healthy
